version: '3.1'

services:

    spring_db:
        image: postgres:16.1
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - 5432:5432
        restart: unless-stopped

    mikrostoritev:
        build: .
        restart: always
        ports:
            - 8280:8280
        environment:
            - SPRING_PROFILES_ACTIVE=psql
            - SPRING_DATASOURCE_URL=jdbc:postgresql://spring_db:5432/postgres
        depends_on:
            - spring_db

volumes:
    postgres:
